import { View, Text, ScrollView } from 'react-native'
import React,{useRef} from 'react'
import {useGLTF} from '@react-three/drei/native';
import useControls from "r3f-native-orbitcontrols"
import motorScene from '../../assets/electric_motor.glb';

const MotorModel = (props) => {
    const [OrbitControls, events] = useControls()
    const { nodes, materials } = useGLTF(motorScene);
    const islandRef = useRef();
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-4.174, 13.297, -25.018]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_Car_Paint_0.geometry}
            material={materials.Car_Paint}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_Black_Plastic_0.geometry}
            material={materials.Black_Plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_lIndicator_Inside_0.geometry}
            material={materials.lIndicator_Inside}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_Lights_Inside_0.geometry}
            material={materials.Lights_Inside}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_TailLights_Inside_0.geometry}
            material={materials.TailLights_Inside}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_Rubber_0.geometry}
            material={materials.Rubber}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_EngineBay_0.geometry}
            material={materials.EngineBay}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chassis_rIndicator_Inside_0.geometry}
            material={materials.rIndicator_Inside}
          />
          <group position={[0.322, 1.48, -0.452]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rlStrut_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[0.433, -0.013, 0.073]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rlWheel_Wheel_Metal_0.geometry}
                material={materials.Wheel_Metal}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rlBrakeDisk_Brake_Rotor_0.geometry}
                material={materials.Brake_Rotor}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rlTire_Tire_0.geometry}
                material={materials.Tire}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rlBrakeCaliper_Brake_Caliper001_0.geometry}
              material={materials["Brake_Caliper.001"]}
              position={[0.433, -0.013, 0.073]}
            />
          </group>
          <group position={[-0.277, -1.575, -0.487]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.frStrut_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[-0.503, 0.042, 0.113]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.frWheelMount_Metal_Rough_0.geometry}
                material={materials.Metal_Rough}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.frWheel_Wheel_Metal_0.geometry}
                material={materials.Wheel_Metal}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.frBrakeDisk_Brake_Rotor_0.geometry}
                material={materials.Brake_Rotor}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.frTire_Tire_0.geometry}
                material={materials.Tire}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.frBrakeCaliper_Brake_Caliper001_0.geometry}
                material={materials["Brake_Caliper.001"]}
              />
            </group>
          </group>
          <group position={[0.277, -1.575, -0.487]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.flStrut_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[0.503, 0.042, 0.113]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.flWheelMount_Metal_Rough_0.geometry}
                material={materials.Metal_Rough}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.flWheel_Wheel_Metal_0.geometry}
                material={materials.Wheel_Metal}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.flBrakeDisk_Brake_Rotor_0.geometry}
                material={materials.Brake_Rotor}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.flTire_Tire_0.geometry}
                material={materials.Tire}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.flBrakeCaliper_Brake_Caliper001_0.geometry}
                material={materials["Brake_Caliper.001"]}
              />
            </group>
          </group>
          <group position={[-0.322, 1.48, -0.452]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rrStrut_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[-0.433, -0.013, 0.073]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rrWheel_Wheel_Metal_0.geometry}
                material={materials.Wheel_Metal}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rrTire_Tire_0.geometry}
                material={materials.Tire}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rrBrakeDisk_Brake_Rotor_0.geometry}
                material={materials.Brake_Rotor}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rrBrakeCaliper_Brake_Caliper001_0.geometry}
              material={materials["Brake_Caliper.001"]}
              position={[-0.433, -0.013, 0.073]}
            />
          </group>
          <group position={[-0.73, -2.077, 0.101]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightRight_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightRight_Black_Plastic_0.geometry}
              material={materials.Black_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightRight_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightRight_Lights_Inside_0.geometry}
              material={materials.Lights_Inside}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightRightGlass_Clear_Plastic_0.geometry}
              material={materials.Clear_Plastic}
              position={[0.024, -0.206, -0.039]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.HeadlightRightGlass_Back_Clear_Plastic_lines_0.geometry
              }
              material={materials.Clear_Plastic_lines}
              position={[0.024, -0.205, -0.039]}
            />
          </group>
          <group position={[0, -2.275, -0.314]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper_lIndicator_Inside_0.geometry}
              material={materials.lIndicator_Inside}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper_FogLights_Inside_0.geometry}
              material={materials.FogLights_Inside}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper_rIndicator_Inside_0.geometry}
              material={materials.rIndicator_Inside}
            />
            <group position={[0, -0.236, 0.093]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.IndicatorFrontGlass_Clear_Plastic_0.geometry}
                material={materials.Clear_Plastic}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorFrontGlass_Clear_PlasticIndicator_0.geometry
                }
                material={materials.Clear_PlasticIndicator}
              />
            </group>
            <group position={[0, -0.172, 0.105]}>
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorFrontGlass_Back_Clear_Plastic_lines_0.geometry
                }
                material={materials.Clear_Plastic_lines}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorFrontGlass_Back_Clear_PlasticIndicator_lines_0
                    .geometry
                }
                material={materials.Clear_PlasticIndicator_lines}
              />
            </group>
            <group position={[0, 0.029, -0.311]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.fLip_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.fLip_Metal_Rough_0.geometry}
                material={materials.Metal_Rough}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fBumper001_Mesh_0.geometry}
              material={materials.Mesh}
              position={[0, -0.092, -0.132]}
            />
          </group>
          <group position={[0, 0.942, 0.65]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Trunk_Black_Plastic_0.geometry}
              material={materials.Black_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Trunk_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Spoiler_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rWindsheild_Rubber_0.geometry}
              material={materials.Rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rWindsheild_WindowsBlack_0.geometry}
              material={materials.WindowsBlack}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rWindsheild_Windows_0.geometry}
              material={materials.Windows}
            />
          </group>
          <group position={[-0.866, -1.501, 0.137]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.frQuarterPanel_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.frQuarterPanel_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[-0.193, 0.64, -0.151]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.IndicatorRight_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.IndicatorRight_rIndicator_Inside_0.geometry}
                material={materials.rIndicator_Inside}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorRightGlass_Clear_PlasticIndicator_0.geometry
                }
                material={materials.Clear_PlasticIndicator}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorRightGlass_Back_Clear_PlasticIndicator_lines_0
                    .geometry
                }
                material={materials.Clear_PlasticIndicator_lines}
              />
            </group>
          </group>
          <group position={[-1.026, -0.687, 0.059]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rDoor_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rDoor_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <group position={[0.134, 0.294, 0.164]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rMirror_mirrorRight_0.geometry}
                material={materials.mirrorRight}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.rMirror_Car_Paint_0.geometry}
                material={materials.Car_Paint}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rWindow_Rubber_0.geometry}
              material={materials.Rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rWindow_Windows_0.geometry}
              material={materials.Windows}
            />
          </group>
          <group position={[0.867, -1.501, 0.141]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.flQuarterPanel_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.flQuarterPanel_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <group position={[0.193, 0.64, -0.154]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.IndicatorLeft_Rubber_0.geometry}
                material={materials.Rubber}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.IndicatorLeft_lIndicator_Inside_0.geometry}
                material={materials.lIndicator_Inside}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorLeftGlass_Back_Clear_PlasticIndicator_lines_0
                    .geometry
                }
                material={materials.Clear_PlasticIndicator_lines}
                position={[-0.001, 0, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.IndicatorLeftGlass_Clear_PlasticIndicator_0.geometry
                }
                material={materials.Clear_PlasticIndicator}
                position={[-0.001, 0, 0]}
              />
            </group>
          </group>
          <group position={[1.026, -0.687, 0.059]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lDoor_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lDoor_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <group position={[-0.134, 0.294, 0.164]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.lMirror_mirrorLeft_0.geometry}
                material={materials.mirrorLeft}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.lMirror_Car_Paint_0.geometry}
                material={materials.Car_Paint}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lWindow_Rubber_0.geometry}
              material={materials.Rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lWindow_Windows_0.geometry}
              material={materials.Windows}
            />
          </group>
          <group position={[0, 0, -0.011]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fWindsheild_Rubber_0.geometry}
              material={materials.Rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fWindsheild_WindowsBlack_0.geometry}
              material={materials.WindowsBlack}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.fWindsheild_Windows_0.geometry}
              material={materials.Windows}
            />
            <group position={[0, -0.079, 0.588]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mirror_Grey_Plastic_0.geometry}
                material={materials.Grey_Plastic}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mirror_WindowsBlack_0.geometry}
                material={materials.WindowsBlack}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mirror_mirrorMiddle_0.geometry}
                material={materials.mirrorMiddle}
              />
            </group>
          </group>
          <group position={[0, 0, -0.011]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.TaillightGlass_Taillight_Cover_0.geometry}
              material={materials.Taillight_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.TaillightGlass_Back_Taillight_Cover_lines_0.geometry
              }
              material={materials.Taillight_Cover_lines}
            />
          </group>
          <group position={[0, 0, -0.011]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interior_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SunFlaps_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0, 0.011, 0.636]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.rSeat_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[-0.453, 0.211, -0.322]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lSeat_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0.453, 0.211, -0.318]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Dash_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SteeringWheel_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0.4, -0.268, 0.104]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.GasPedal_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0.279, -0.991, -0.158]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.BrakePedal_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0.332, -0.995, -0.148]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ClutchPedal_Grey_Plastic_0.geometry}
              material={materials.Grey_Plastic}
              position={[0.401, -0.988, -0.148]}
            />
          </group>
          <group position={[-0.351, 2.299, -0.543]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Exhaust_Chrome001_0.geometry}
              material={materials["Chrome.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Exhaust_Mesh_0.geometry}
              material={materials.Mesh}
            />
          </group>
          <group position={[0.73, -2.077, 0.101]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightLeft_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightLeft_Black_Plastic_0.geometry}
              material={materials.Black_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightLeft_Metal_Rough_0.geometry}
              material={materials.Metal_Rough}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightLeft_Lights_Inside_0.geometry}
              material={materials.Lights_Inside}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.HeadlightLeftGlass_Clear_Plastic_0.geometry}
              material={materials.Clear_Plastic}
              position={[-0.024, -0.206, -0.039]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.HeadlightLeftGlass_Back_Clear_Plastic_lines_0.geometry
              }
              material={materials.Clear_Plastic_lines}
              position={[-0.024, -0.205, -0.039]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rlShock_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
            position={[0.644, 1.464, 0.043]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.flShock_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
            position={[0.5, -1.526, 0.002]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rrShock_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
            position={[-0.644, 1.464, 0.043]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.frShock_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
            position={[-0.5, -1.526, 0.002]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rBumperPlastic_Rubber_0.geometry}
            material={materials.Rubber}
            position={[0, 2.442, -0.469]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.rBumper_Car_Paint_0.geometry}
            material={materials.Car_Paint}
            position={[0, 2.417, -0.095]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hood_Car_Paint_0.geometry}
            material={materials.Car_Paint}
            position={[0, -0.749, 0.261]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.EngineBay_Metal_Rough_0.geometry}
            material={materials.Metal_Rough}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.GasCap_Car_Paint_0.geometry}
            material={materials.Car_Paint}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(motorScene);

export default MotorModel